backend:
  name: git-gateway
  repo: github.com/AlexS2106/thunder-island
  branch: main
media_folder: static/images
public_folder: /images
collections:
  - name: 'recipes'
    label: 'Recipes'
    folder: 'content/food-and-health'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Main Categories", name: "mainCategories", widget: "list" }
      - { label: "Subcategories", name: "subCategories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: 'Date', name: 'date', widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Portrait Image", name: "portraitImage", widget: "image" }
      - { label: "Landscape Image", name: "landscapeImage", widget: "image" }
      - { label: "Banner Image", name: "bannerImage", widget: "image" }
      - { label: "Pin", name: "pin", widget: "image" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Photographer", name: "photographer", widget: "string"}
      - { label: "Comments", name: "true", widget: "boolean" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Blurb", name: "blurb", widget: "boolean" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: 'profile'
    label: 'Profiles'
    folder: 'content/about'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Portrait Image", name: "portraitImage", widget: "image" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Photographer", name: "photographer", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }    
  