backend:
  name: git-gateway
  repo: github.com/AlexS2106/thunder-island
  branch: main
media_folder: static/images
public_folder: /images
collections:

  - name: 'profile'
    label: 'Profiles'
    folder: 'content/about'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { 
          label: "Type", 
          name: "type", 
          widget: "select", 
          options: [ "profile" ]
        }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Portrait Image", name: "portraitImage", widget: "image", required: false }
      - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Photographer", name: "photographer", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" } 

  - name: 'health'
    label: 'Health'
    folder: 'content/food-and-health/health'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { 
          label: "Type", 
          name: "type", 
          widget: "select",
          multiple: true, 
          options: [ "post", "short" ]
        }
      - { label: "Slug", name: "slug", widget: "string" }
      - { 
          label: "Main Categories", 
          name: "mainCategories", 
          widget: "select", 
          options: [ "Food and Health" ],
          default: [ "Food And Health" ]
        }
      - {
          label: "Subcategories",
          name: "subcategories",
          widget: "select",
          options: [ "Health" ],
          default: [ "Health" ]
        }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "select", 
          multiple: true, 
          required: false, 
          options: 
            ["Information", "Exercise", "Diets", "Living" ]
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Portrait Image", name: "portraitImage", widget: "image", required: false}
      - { label: "Landscape Image", name: "landscapeImage", widget: "image", required: false}
      - { label: "Banner Image", name: "bannerImage", widget: "image", required: false }
      - { label: "Pin", name: "pin", widget: "image", required: false }
      - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Photographer", name: "photographer", widget: "string", required: false}
      - { label: "Comments", name: "comments", widget: "boolean", default: true }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: 'recipes'
    label: 'Recipes'
    folder: 'content/food-and-health/recipes'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { 
          label: "Type", 
          name: "type", 
          widget: "select", 
          multiple: true,
          options: [ "post", "short", "recipe" ]
        }
      - { label: "Slug", name: "slug", widget: "string" }
      - { 
          label: "Main Categories", 
          name: "mainCategories", 
          widget: "select", 
          options: [ "Food and Health" ],
          default: [ "Food And Health" ]
        }
      - {
          label: "Subcategories",
          name: "subcategories",
          widget: "select",
          options: [ "Recipes" ],
          default: [ "Recipes" ]
        }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "select", 
          multiple: true, 
          required: false, 
          options: 
            [
              { label: "Breakfast and Lunch", value: "breakfast-and-lunch" },
              { label: "Main Dish", value: "main" },
              { label: "Side Dish", value: "side" },
              { label: "Salads and Soups", value: "salads-and-soups" },
              { label: "Snacks and Appetisers", value: "snacks-and-appetisers" },
              { label: "Beef and Lamb", value: "beef-and-lamb" },
              { label: "Chicken and Pork", value: "chicken-and-pork" },
              { label: "Dairy, Eggs, Nuts and Fruit", value: "dairy-eggs-nuts-and-fruit" },
              { label: "Fish and Seafood", value: "fish-and-seafood" },
              { label: "Vegetables", value: "vegetables" },
              { label: "Low Net Carbs", value: "low-net-carbs" },
              { label: "Low Total Carbs", value: "low-total-carbs" },
              { label: "Low Calorie", value: "low-calorie" },
              { label: "Paleo", value: "paleo" },
              { label: "Paleo-ish", value: "paleo-ish" },
              { label: "Carnivore", value: "carnivore" },
              { label: "All Recipes", value: "all" }
            ]
        }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Portrait Image", name: "portraitImage", widget: "image" }
      - { label: "Landscape Image", name: "landscapeImage", widget: "image" }
      - { label: "Banner Image", name: "bannerImage", widget: "image", required: false }
      - { label: "Pin", name: "pin", widget: "image" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Photographer", name: "photographer", widget: "string", required: false}
      - { label: "Comments", name: "comments", widget: "boolean", default: true }
      - { label: "Recipe", name: "recipe", widget: "markdown" }
      - { label: "Nutrition", name: "nutrition", widget: "file", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: 'learn-english'
    label: 'Learn English'
    folder: 'content/learn-english'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { 
        label: "Type", 
        name: "type", 
        widget: "select", 
        multiple: true, 
        options: 
          ["post", "short", "lesson", "practice"]
        }
      - { 
        label: "Related Lessons or Exercises", 
        name: "related", 
        widget: "related", 
        collection: "practice", 
        required: false
        }
      - { label: "Slug", name: "slug", widget: "string" } 
      - { 
          label: "Main Category", 
          name: "mainCategories", 
          widget: "select", 
          options: [ "Learn English" ],
          default: [ "Learn English" ]
        }
      - { 
        label: "Subcategories", 
        name: "subcategories", 
        widget: "select", 
        multiple: true, 
        options: ["Lingua Node", "Lingua Nodule", "Lingua Practice" ]
        }
      - { 
        label: "CEFR Level", 
        name: "cefr", 
        widget: "select", 
        multiple: true, 
        options: ["A1", "A2", "B1", "B2", "C1", "C2"]
        }
      - { 
        label: "Lingua Cluster", 
        name: "cluster", 
        widget: "select", 
        multiple: true, 
        options:
        [
          {label: "Adjectives", value: "adjectives" },
          {label: "Adverbs", value: "adverbs" },
          {label: "Past Tense", value: "past-tense" },
          {label: "Present Tense", value: "present-tense" },
          {label: "Future Tense", value: "future-tense" },
          {label: "Questions", value: "questions" }
        ]
        }
      - { label: "Author", name: "author", widget: "string", required: false}
      - { label: "Portrait Image", name: "portraitImage", widget: "image", required: false }
      - { label: "Landscape Image", name: "landscapeImage", widget: "image", required: false }
      - { label: "Banner Image", name: "bannerImage", widget: "image", required: false }
      - { label: "Pin", name: "pin", widget: "image", required: false }
      - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Photographer", name: "photographer", widget: "string", required: false }
      - { label: "Diagram", name: "diagram", widget: "image", required: false}
      - { label: "Animation", name: "animation", widget: "image", required: false}
      - { label: "Animator", name: "animator", widget: "string", required: false}
      - { label: "Comments", name: "comments", widget: "boolean", default: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }  

  - name: 'portfolios'
    label: 'Portfolios'
    folder: 'content/portfolios'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { 
        label: "Type", 
        name: "type", 
        widget: "select", 
        multiple: true, 
        options: 
          [ "post", "short", "album" ]
        }
      - { label: "Slug", name: "slug", widget: "string" } 
      - { 
          label: "Main Category", 
          name: "mainCategories", 
          widget: "select", 
          options: [ "Portfolios" ],
          default: [ "Portfolios" ]
        }
      - { 
        label: "Subcategories", 
        name: "subcategories", 
        widget: "select", 
        multiple: true, 
        options: 
        [
          { label: "Web Development", value: "web-dev" }, 
          { label: "Expats in Malta", value: "expats-in-malta" }, 
          { label: "Writing", value: "writing" },  
        ]
        }
      - { 
        label: "Tags", 
        name: "tags", 
        widget: "select", 
        multiple: true, 
        options:
        [
          {label: "Family Life", value: "family-life" },
          {label: "Reviews", value: "reviews" },
          {label: "Stories or Poems", value: "stories-and-poems" },
        ]
        }
      - { 
        label: "Album", 
        name: "album", 
        widget: "select", 
        multiple: true, 
        required: false,
        options:
        [
          {label: "Eerie Malta", value: "eerie-malta" },
          {label: "Blue Malta", value: "blue-malta" },
          {label: "Wildlife in Malta", value: "wildlife-in-malta" },
          {label: "Walking in Malta", value: "walking-in-malta" },
          {label: "Playing in Malta", value: "playing-in-malta" },
          {label: "The Beach in Malta", value: "beach-in-malta" },
        ]
        }
      - { label: "Author", name: "author", widget: "string", required: false}
      - { label: "Portrait Image", name: "portraitImage", widget: "image", required: false }
      - { label: "Landscape Image", name: "landscapeImage", widget: "image", required: false }
      - { label: "Banner Image", name: "bannerImage", widget: "image", required: false }
      - { label: "Pin", name: "pin", widget: "image", required: false }
      - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Photographer", name: "photographer", widget: "string", required: false }
      - { label: "Comments", name: "comments", widget: "boolean", default: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false } 
